"""Initial migration with all existing tables

Revision ID: ee980f9ccd4f
Revises: 
Create Date: 2026-02-22 21:07:12.951836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee980f9ccd4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_attempts_old', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_login_attempts_attempted_at'))
        batch_op.drop_index(batch_op.f('idx_login_attempts_ip_address'))
        batch_op.drop_index(batch_op.f('idx_login_attempts_ip_time'))
        batch_op.drop_index(batch_op.f('idx_login_attempts_success'))
        batch_op.drop_index(batch_op.f('idx_login_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_attempted_at'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_username'))

    op.drop_table('login_attempts_old')
    with op.batch_alter_table('batch_processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_batch_jobs_created_at'))
        batch_op.drop_index(batch_op.f('idx_batch_jobs_status'))
        batch_op.drop_index(batch_op.f('idx_batch_jobs_task_id'))
        batch_op.drop_index(batch_op.f('idx_batch_jobs_user_id'))
        batch_op.drop_index(batch_op.f('idx_batch_jobs_user_status'))

    with op.batch_alter_table('document_type_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_doc_stats_doc_type'))

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_attempted_at'), ['attempted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_email'), ['email'], unique=False)

    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('task_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('batch_job_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('validation_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('validation_errors', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_scan_history_created_at'))
        batch_op.drop_index(batch_op.f('idx_scan_history_document_type'))
        batch_op.create_index(batch_op.f('ix_scan_history_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_history_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'batch_processing_jobs', ['batch_job_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_users_created_at'))
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_is_active'))
        batch_op.drop_index(batch_op.f('idx_users_username'))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('idx_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=1)
        batch_op.create_index(batch_op.f('idx_users_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('last_login',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_scan_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_scan_history_task_id'))
        batch_op.create_index(batch_op.f('idx_scan_history_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_scan_history_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('validation_errors')
        batch_op.drop_column('validation_status')
        batch_op.drop_column('batch_job_id')
        batch_op.drop_column('task_id')
        batch_op.drop_column('status')
        batch_op.drop_column('filename')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_email'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_attempted_at'))

    with op.batch_alter_table('document_type_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_doc_stats_doc_type'), ['document_type'], unique=False)

    with op.batch_alter_table('batch_processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_batch_jobs_user_status'), ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_batch_jobs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_batch_jobs_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_batch_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_batch_jobs_created_at'), ['created_at'], unique=False)

    op.create_table('login_attempts_old',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=False),
    sa.Column('attempted_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts_old', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_attempted_at'), ['attempted_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_login_attempts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_login_attempts_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('idx_login_attempts_ip_time'), ['ip_address', 'attempted_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_login_attempts_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('idx_login_attempts_attempted_at'), ['attempted_at'], unique=False)

    # ### end Alembic commands ###
